# ASP.NET Core Build and Publish
# Build and deploy ASP.NET Core app to Azure

pool: 'Default'

variables:
  imageRepository: 'amir2023'
  imageName: 'aspbasicserver'
steps:
- task: PowerShell@2
  displayName: 'Run PowerShell Script'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output "Hello World"
      Write-Output "$(dir)"
      Write-Output "$(System.ArtifactsDirectory)"
- task: PowerShell@2
  displayName: 'Run Script'
  inputs:
    targetType: 'filePath'
    filePath: 'changeversion.ps1'

- task: DotNetCoreCLI@2
  displayName: 'Build ASP.NET App'
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish ASP.NET App'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    arguments: '-f $(Build.SourcesDirectory)/Dockerfile -t $(imageName):$(Build.BuildId)'


- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    command: 'push'
    repository: '$(imageRepository)'
    arguments: '$(imageName):1.0'

