trigger:
- azure-piplines
   
pool:
  vmImage: 'Azure Pipelines'
   

variables:
  imageName: 'pipelines-javascript-docker'
  DOCKER_BUILDKIT: 1
    
steps:
- task: Docker@2
  displayName: Build an image
