version: '3'
services:
  app:
    image: amir2023/aspbasicserver  
    container_name: app
    ports: 
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
